CC = gcc
LIBS = -lglut -lGLU -lGL -lm
INCLUDES = -I/usr/include/GL
CCOPTS = -Wall -o3 -std=gnu99 $(INCLUDES)

.phony clean all

all: malloc

malloc.o: malloc.c malloc.h
	  gcc $(CCOPTS) -c -o malloc.o malloc.c

.test: malloc_test.c $(INCLUDES) $(CC) $(LIBS)
