CC=gcc
CFLAGS = -Wall -Wextra -std=c99
LDFLAGS = 

SRCS = malloc.c
OBJS = $(SRCS:.c=.o)
TARGET = malloc

.phony: all clean

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $^

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $^

clean:
	rm -f $(OBJS) $(TARGET)

.test: test.c $(OBJS)

