CC=gcc
CFLAGS = -Wall -Wextra -std=c99
LDFLAGS = 

SRCS = buddy_allocator.c
OBJS = $(SRCS:.c=.o)
TARGET = buddy_allocator

.phony: all clean

$(TARGET): $(OBJS)
           $(CC) $(LDFLAGS) -o $@ $^

%.o: %.c
    $(CC) $(CFLAGS) -c -o $@ $^

clean:
    rm -f $(OBJS) $(TARGET)

